config/routes.rb
Monster::Application.routes.draw do
  resources :singlescenes

  resources :comsettings

  resources :rasberry_pis

  match '/', to: 'static_pages#home', via: 'get', as: :home
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/changecomsettings', to: 'static_pages#changecomsettings', via: 'get', as: :changecomsettings
  resources :scenes
  post 'rasberry_pis/shutdown' => 'rasberry_pis#shutdown', as: :shutdown_pi
  post 'scenes/:id/invoke' => 'scenes#invokescene', as: :invoke
  post 'scenes/stop_animation' => 'scenes#stop_animation', as: :stop_animation
  post 'scenes/stop_ambient' => 'scenes#stop_ambient', as: :stop_ambient
  post 'scenes/start_ambient' => 'scenes#start_ambient', as: :start_ambient
  post 'scenes/sequential_mode' => 'scenes#sequential_mode', as: :sequential_mode
  get 'singlescenes/1/edit' => 'singlescenes#edit', as: :single_mode
  post 'scenes/random_mode' => 'scenes#random_mode', as: :random_mode
  post 'scenes/refresh_scenes' => 'scenes#refresh_scenes', as: :refresh_scenes
  post 'rasberry_pis/reconnect_to_arduino' => 'rasberry_pis#reconnect_to_arduino', as: :reconnect_to_arduino
  

  root 'static_pages#home'

  

end

app/models/singlescene.rb
class Singlescene < ActiveRecord::Base
end

app/controllers/singlescenes_controller.rb
class SinglescenesController < ApplicationController
  before_action :set_singlescene, only: [:show, :edit, :update, :destroy]
  
  # GET /singlescenes
  # GET /singlescenes.json
  def index
    @singlescenes = Singlescene.all
    @scenes = Scene.all
       
  end

  # GET /singlescenes/1
  # GET /singlescenes/1.json
  def show
  end

  # GET /singlescenes/new
  def new
    @singlescene = Singlescene.new
  end

  # GET /singlescenes/1/edit
  def edit
  end

  # POST /singlescenes
  # POST /singlescenes.json
=begin
  def create
    @singlescene = Singlescene.new(singlescene_params)

    respond_to do |format|
      if @singlescene.save
        format.html { redirect_to @singlescene, notice: 'Singlescene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @singlescene }
      else
        format.html { render action: 'new' }
        format.json { render json: @singlescene.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # PATCH/PUT /singlescenes/1
  # PATCH/PUT /singlescenes/1.json
  def update
   begin
    respond_to do |format|
      if @singlescene.update(singlescene_params)
        
        firstchar = @singlescene.slot.first
        @comsettings = Comsetting.all
        $PORT.write("@S" + firstchar.to_s)
        sleep 2
        $PORT.write("@P2")
        
        format.html { redirect_to @singlescene, notice: 'Single Mode has been enabled on ' + firstchar.to_s }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @singlescene.errors, status: :unprocessable_entity }
      end
    end
   rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
   else   
   end
  end

=begin
  # DELETE /singlescenes/1
  # DELETE /singlescenes/1.json
  def destroy
    @singlescene.destroy
    respond_to do |format|
      format.html { redirect_to singlescenes_url }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singlescene
      @singlescene = Singlescene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def singlescene_params
      params.require(:singlescene).permit(:slot)
    end
end

app/helpers/singlescenes_helper.rb
module SinglescenesHelper
end

app/views/singlescenes/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="well">
              <%= form_for @singlescene, :html => {:class => "form-horizontal"} do |f| %>
				  <% if @singlescene.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@singlescene.errors.count, "error") %> prohibited this jumpsquare from being saved:</h2>
				
				      <ul>
				      <% @singlescene.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>   
				  
				  <% @scenes = Scene.all %>
					<% slotarray=[] %>
					<% @scenes.each do |scene| %>
			      		  <% if scene.enabled == true %>
			      		  	<% scenenumber = scene.id - 1 %>	 
			     			 <% if (scene.id - 1).to_s == "10"
			        				scenenumber = "A"
			     				elsif (scene.id - 1).to_s == "11"
			        				scenenumber = "B"
			     				elsif (scene.id - 1).to_s == "12"
			        				scenenumber = "C"
			     				elsif (scene.id - 1).to_s == "13"
			        				scenenumber = "D"
			     				elsif (scene.id - 1).to_s == "14"
			       					scenenumber = "E"
			    				end %>
			    			<% slotarray << scenenumber.to_s + ". " + scene.name.to_s %>
			           <% end %>              
			     <% end %>
				       
                <fieldset>
                  <legend>Configure Single Scene Mode</legend>
                  <p>
				    Only enabled slots can be chosen. If you do not see you slot available, go the <%= link_to 'MonsterShield settings', scenes_path %> page to enable the slot.
				    <br>
				  </p>
                  <div class="form-group">
                  	<%= f.label :slot, "Choose a Slot:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.select :slot, slotarray, {}, include_blank: false, :class => "form-control" %>	 
                    </div>
                  </div>                                
                  <center>
	                  <div class="form-group">	                  	                  
	                      <%= f.submit "Save and Enable Single Slot Mode", class: 'btn btn-primary'%>	                    
	                  </div> 
			<% end %>	                              
	                  <%= link_to :back, class: "pull-left", :method => :get do %>
	        			 Back
	    			  <% end %>
	                     
	                  <%= link_to :home, class: "pull-right", :method => :get do %>
	        			Home
	    			  <% end %>       
                  </center>
                </fieldset>
             
            </div>
          </div>
        </div>
</html>

app/views/singlescenes/edit.html.erb
<% provide(:title, 'Edit Single Slot Mode') %>
<br>
<%= render 'form' %>

app/views/singlescenes/index.html.erb
<h1>Listing singlescenes</h1>

<table>
  <thead>
    <tr>
      <th>Slot</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @singlescenes.each do |singlescene| %>
      <tr>
        <td><%= singlescene.slot %></td>
        <td><%= link_to 'Show', singlescene %></td>
        <td><%= link_to 'Edit', edit_singlescene_path(singlescene) %></td>
        <td><%= link_to 'Destroy', singlescene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Singlescene', new_singlescene_path %>

app/views/singlescenes/newNOMORESINGLES.html.erb
<h1>New singlescene</h1>

<%= render 'form' %>

<%= link_to 'Back', singlescenes_path %>

app/views/singlescenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slot:</strong>
  <%= @singlescene.slot %>
</p>

<%= link_to 'Edit', edit_singlescene_path(@singlescene) %> |
<%= link_to 'Back', edit_singlescene_path(@singlescene) %> |
<%= link_to 'MonsterRemote Home', :home %>