config/routes.rb
Monster::Application.routes.draw do
  resources :singlescenes

  resources :comsettings

  resources :rasberry_pis

  match '/', to: 'static_pages#home', via: 'get', as: :home
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/changecomsettings', to: 'static_pages#changecomsettings', via: 'get', as: :changecomsettings
  resources :scenes
  post 'rasberry_pis/shutdown' => 'rasberry_pis#shutdown', as: :shutdown_pi
  post 'scenes/:id/invoke' => 'scenes#invokescene', as: :invoke
  post 'scenes/stop_animation' => 'scenes#stop_animation', as: :stop_animation
  post 'scenes/stop_ambient' => 'scenes#stop_ambient', as: :stop_ambient
  post 'scenes/start_ambient' => 'scenes#start_ambient', as: :start_ambient
  post 'scenes/sequential_mode' => 'scenes#sequential_mode', as: :sequential_mode
  get 'singlescenes/1/edit' => 'singlescenes#edit', as: :single_mode
  post 'scenes/random_mode' => 'scenes#random_mode', as: :random_mode
  post 'scenes/refresh_scenes' => 'scenes#refresh_scenes', as: :refresh_scenes
  post 'rasberry_pis/reconnect_to_arduino' => 'rasberry_pis#reconnect_to_arduino', as: :reconnect_to_arduino
  

  root 'static_pages#home'

  

end

app/models/scene.rb
class Scene < ActiveRecord::Base
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  
  before_action :set_scene, only: [:show, :edit, :update, :destroy]
  
  # GET /scenes
  # GET /scenes.json
  
  def index
    @scenes = Scene.all
  end
  
  def refresh_scenes
   @scenes = Scene.all
    begin
      sleep 2
      $PORT.read_timeout = 2000
      $PORT.write("@O")
      garbagescenes = $PORT.read.to_s.chomp!
      @monsterscenes = garbagescenes.delete "$O"
      

      @scenes.each do |scene|
        if @monsterscenes[scene.id - 1] =="1"
          scene.enabled = true
          scene.save
        else
          scene.enabled = false
          scene.save
        end
      end
     redirect_to :back
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
    end
  end
  
  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
    
  end

  # POST /scenes
  # POST /scenes.json
  
  #remove ability to create more scenes
=begin
  
 
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scene }
      else
        format.html { render action: 'new' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

=end 

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
   begin
      
    
    respond_to do |format|
     
      if @scene.update(scene_params)
            
            @scenenumber = @scene.id - 1
              if (@scene.id - 1).to_s == "10"      
                 @scenenumber = "A"  
              elsif (@scene.id - 1).to_s == "11"
                 @scenenumber = "B"
              elsif (@scene.id - 1).to_s == "12"
                 @scenenumber = "C"
              elsif (@scene.id - 1).to_s == "13"
                 @scenenumber = "D"
              elsif (@scene.id - 1).to_s == "14"
                  @scenenumber = "E" 
              end
              
              if @scene.enabled
                $PORT.write("@+" + @scenenumber.to_s)
              else
                $PORT.write("@-" + @scenenumber.to_s)
              end
        format.html { redirect_to :scenes, notice: 'Scene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
     else 
   end
  end

  
  # DELETE /scenes/1
  # DELETE /scenes/1.json
  # we can't have any mistakes
=begin
  
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url }
      format.json { head :no_content }
    end
  end

=end

  #This will tell a button tos send a command to the arduino to start a scene
  def invokescene
    # require 'serialport'
    sceneid = "@T" + (params[:id].to_i-1).to_s
    
    if (params[:id].to_i-1).to_s == "10"
        sceneid = "@TA"
     elsif (params[:id].to_i-1).to_s == "11"
        sceneid = "@TB"
     elsif (params[:id].to_i-1).to_s == "12"
        sceneid = "@TC"
     elsif (params[:id].to_i-1).to_s == "13"
        sceneid = "@TD"
     elsif (params[:id].to_i-1).to_s == "14"
        sceneid = "@TE"
    end
    
    begin
        $PORT.write sceneid  
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
        respond_to do |format|
          format.html {redirect_to :back }

        end
    end 
  end
  
  def stop_animation
    begin
        $PORT.write("@*")
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: 'Scene has been Stopped.' }
        format.json { head :no_content }
      end
    end
  end

  def stop_ambient
    begin
        $PORT.write("@A0")
        sleep 1
        $PORT.write("@*")
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: 'Ambient Mode has been Stopped.' }
        format.json { head :no_content }
      end
    end
  end
  
  def start_ambient
    begin
        $PORT.write("@A1")
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Ambient Mode has been Started.' }
        format.json { head :no_content }
      end
    end
  end
  
  def sequential_mode
    begin
        $PORT.write("@P0")
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Sequential Mode has been Started.' }
        format.json { head :no_content }
      end
    end
  end
  
  
  def random_mode
    begin
        $PORT.write("@P1")
    rescue
        $CONNECTED = 'fail'
        redirect_to :changecomsettings
    else
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Random Mode has been Started.' }
        format.json { head :no_content }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:name, :enabled)
    end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="well">
              <%= form_for @scene, :html => {:class => "form-horizontal"} do |f| %>
				  <% if @scene.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this jumpsquare from being saved:</h2>
				
				      <ul>
				      <% @scene.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>        
                <fieldset>
                  <legend>Scene: <%= @scene.name %></legend>
                  <div class="form-group">
                  	<%= f.label :name, "Scene Name:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.text_field :name, :class => "form-control" %>	 
                    </div>
                  </div>
                  <br>                  
                  <div class="form-group">
                  	<%= f.label :enabled, "Enabled:", :class => "col-lg-4 control-label" %>
                    <div class="col-lg-4">
                      <%= f.check_box :enabled, :class => "form-control" %>
                    </div>
                  </div>                                  
                  <center>
	                  <div class="form-group">	                  	                  
	                      <%= f.submit class: 'btn btn-primary'%>	                    
	                  </div> 
			<% end %>	                              
	                  <%= link_to :back, class: "pull-left", :method => :get do %>
	        			 Back
	    			  <% end %>
	                     
	                  <%= link_to :home, class: "pull-right", :method => :get do %>
	        			Home
	    			  <% end %>       
                  </center>
                </fieldset>
             
            </div>
          </div>
        </div>
</html>

app/views/scenes/edit.html.erb
<br>
<%= render 'form' %>

app/views/scenes/index.html.erb
<% provide(:title, 'Settings') %>
<!DOCTYPE html>
<html>
  <head>
    <title><% :title %>	</title>
  </head>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<br>
		<center><div id="notice"><span class="label label-success"><%= notice %></span></div><div id="alert"><span class="label label-danger"><%= alert %></span></div></center>
<center><h3>MonsterShield Settings</h3></center>

<body>
	<b>Slot Settings</b><br>
	You can edit the name of each sequence to anything of your choosing. This name will appear on the MonsterRemote homescreen.
	If the animation/scene/sequence is enabled, a button will appear on the MonsterRemote home screen. 
	If animation/scene/sequence is disabled, it removes the button from the home screen. 
	Setting animation/scene/sequence to enabled or disabled will change the configuration of the MonsterShield for that particular slot.
		
</body>
	</div>
</div>
<p></p>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  			<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "Refresh Animations", :refresh_scenes, class: "btn btn-lg btn-default", data: { confirm: " Ambient mode must be turned off to continue. \n Please verify Ambient Mode is turned OFF! \n \n \n Are you sure you want to continue?"}, :method => :post %> 
     		</div>
     	</div>
	</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Sequence</th>
				    <th>Name</th>
				    <th>Enabled</th>
				    <th></th>
                  </tr>
                </thead>
                
                	<tbody>
                		<% @scenes.each do |scene| %>
						      <tr>
						     <% @scenenumber = scene.id - 1 %>	 
						     <% if (scene.id - 1).to_s == "10"
						        @scenenumber = "A"
						     elsif (scene.id - 1).to_s == "11"
						        @scenenumber = "B"
						     elsif (scene.id - 1).to_s == "12"
						        @scenenumber = "C"
						     elsif (scene.id - 1).to_s == "13"
						        @scenenumber = "D"
						     elsif (scene.id - 1).to_s == "14"
						        @scenenumber = "E"
						    end %>
						        <td><%= @scenenumber %></td>
						        <td><%= scene.name %></td>
						        <td><% if scene.enabled == true %>
						        		<%= image_tag("greencheck.png", :alt => "Yes") %>
						        	<% else %>
						        		<%= image_tag("redx.png", :alt => "Yes") %>
						        	<% end %>
						        </td>					        
						        <td><%= link_to 'Edit', edit_scene_path(scene), method: :get, class: "btn btn-warning btn-xs" %></td>
						        
						      </tr>
						    <% end %>
					  </tbody>               
              </table>
</div>
</div>		
<br>
<br>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<body><b>Ambient Settings</b><br>
	Toggle (Start/Stop) Ambient Mode on Slot 0</body>
	</div>
</div>
	<p>	
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  			<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "STOP", :stop_ambient, class: "btn btn-lg btn-danger", data: { confirm: "STOP Ambient loop \n\nAre you sure?"}, :method => :post %> 
     		</div>
     	
  			<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "START", :start_ambient, class: "btn btn-lg btn-success", data: { confirm: "START Ambient loop \n\nAre you sure?"}, :method => :post %> 
     		</div>
     		</div>
     	</div>	
  	</p>
<br>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<body><b>Playback Settings</b><br>
	Change Slot Playback Mode. How will the next slot be selected?</body>
	</div>
</div>
	<p>	
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  			<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "Sequential", :sequential_mode, class: "btn btn-lg btn-info", data: { confirm: "Use 'Sequential'\n\nAre you sure?"}, :method => :post %> 
     		</div>
     	
  			<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "Random", :random_mode, class: "btn btn-lg btn-info", data: { confirm: "Use 'Random'\n\nAre you sure?"}, :method => :post %> 
     		</div>
     		
     		<div style="float:left;margin-right:10px;margin-bottom: 10px;">
      			<%= button_to "Single", :single_mode, class: "btn btn-lg btn-info", :method => :get %> 
     		</div>
     		</div>
     	</div>	
  	</p>
<br>

<%#= link_to 'New Scene', new_scene_path %>
</html>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/new_NOMORESCENES.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scene.name %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @scene.enabled %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %> |
<%= link_to 'MonsterRemote Home', :home %>