config/routes.rb
Monster::Application.routes.draw do
  resources :singlescenes

  resources :comsettings

  resources :rasberry_pis

  match '/', to: 'static_pages#home', via: 'get', as: :home
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/changecomsettings', to: 'static_pages#changecomsettings', via: 'get', as: :changecomsettings
  resources :scenes
  post 'rasberry_pis/shutdown' => 'rasberry_pis#shutdown', as: :shutdown_pi
  post 'scenes/:id/invoke' => 'scenes#invokescene', as: :invoke
  post 'scenes/stop_animation' => 'scenes#stop_animation', as: :stop_animation
  post 'scenes/stop_ambient' => 'scenes#stop_ambient', as: :stop_ambient
  post 'scenes/start_ambient' => 'scenes#start_ambient', as: :start_ambient
  post 'scenes/sequential_mode' => 'scenes#sequential_mode', as: :sequential_mode
  get 'singlescenes/1/edit' => 'singlescenes#edit', as: :single_mode
  post 'scenes/random_mode' => 'scenes#random_mode', as: :random_mode
  post 'scenes/refresh_scenes' => 'scenes#refresh_scenes', as: :refresh_scenes
  post 'rasberry_pis/reconnect_to_arduino' => 'rasberry_pis#reconnect_to_arduino', as: :reconnect_to_arduino
  

  root 'static_pages#home'

  

end

app/models/comsetting.rb
class Comsetting < ActiveRecord::Base
end

app/controllers/comsettings_controller.rb
class ComsettingsController < ApplicationController
  before_action :set_comsetting, only: [:show, :edit, :update, :destroy]

  # GET /comsettings
  # GET /comsettings.json
  def index
    @comsettings = Comsetting.all
  end

  # GET /comsettings/1
  # GET /comsettings/1.json
  def show
  end

  # GET /comsettings/new
  def new
    @comsetting = Comsetting.new
  end


  # GET /comsettings/1/edit
  def edit
  end

  # POST /comsettings
  # POST /comsettings.json
=begin
  
  def create
    @comsetting = Comsetting.new(comsetting_params)

    respond_to do |format|
      if @comsetting.save
        format.html { redirect_to @comsetting, notice: 'Comsetting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comsetting }
      else
        format.html { render action: 'new' }
        format.json { render json: @comsetting.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # PATCH/PUT /comsettings/1
  # PATCH/PUT /comsettings/1.json
  def update
    respond_to do |format|
      if @comsetting.update(comsetting_params)
        format.html { redirect_to :rasberry_pis, notice: 'Comsetting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comsetting.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
=begin

  # DELETE /comsettings/1
  # DELETE /comsettings/1.json
  def destroy
    @comsetting.destroy
    respond_to do |format|
      format.html { redirect_to comsettings_url }
      format.json { head :no_content }
    end
  end

  
=end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comsetting
      @comsetting = Comsetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comsetting_params
      params.require(:comsetting).permit(:comport, :baud)
    end
end

app/helpers/comsettings_helper.rb
module ComsettingsHelper
end

app/views/comsettings/NO_new.html.erb
<h1>New comsetting</h1>

<%= render 'form' %>

<%= link_to 'Back', rasberry_pis_path %>

app/views/comsettings/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="well">
              <%= form_for @comsetting, :html => {:class => "form-horizontal"} do |f| %>
				  <% if @comsetting.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@comsetting.errors.count, "error") %> prohibited this jumpsquare from being saved:</h2>
				
				      <ul>
				      <% @comsetting.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>        
                <fieldset>
                  <legend>Communications Port: <%= @comsetting.comport %> @ <%= @comsetting.baud %> </legend>
                  <div class="form-group">
                  	<%= f.label :comport, " Choose a Communications Port:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.select :comport, ['/dev/ttyACM0','/dev/ttyACM1','/dev/ttyUSB0','/dev/ttyUSB1','/dev/tty.usbmodem411','/dev/tty.usbmodem621','/dev/tty.usbmodem1d11','/dev/tty.usbmodem1421','/dev/tty.usbmodemfd121','/dev/tty.usbmodemfa141','/dev/tty.usbmodemfd131','COM2','COM3','COM4','COM5'], {}, include_blank: false, :class => "form-control" %>	 
                    </div>
                  </div>
                  <br>  
                  <div class="form-group">
                  	<%= f.label :baud, "Choose a baud rate:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.select :baud, [115200,57600,38400,28800,19200,14400,9600,4800,2400,1200,300], {}, include_blank: false, :class => "form-control" %>	 
                    </div>
                  </div>                                       
                  <center>
	                  <div class="form-group">	                  	                  
	                      <%= f.submit class: 'btn btn-primary'%>	                    
	                  </div> 
			<% end %>	                              
	                  <%= link_to :back, class: "pull-left", :method => :get do %>
	        			 Back
	    			  <% end %>
	                     
	                  <%= link_to :home, class: "pull-right", :method => :get do %>
	        			Home
	    			  <% end %>       
                  </center>
                </fieldset>
             
            </div>
          </div>
        </div>
</html>

app/views/comsettings/edit.html.erb
<br>
<%= render 'form' %>

app/views/comsettings/index.html.erb
<h1>Listing comsettings</h1>

<table>
  <thead>
    <tr>
      <th>Communications Port</th>
      <th>Baud Rate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comsettings.each do |comsetting| %>
      <tr>
        <td><%= comsetting.comport %></td>
        <td><%= comsetting.baud %></td>
        <td><%= link_to 'Show', comsetting %></td>
        <td><%= link_to 'Edit', edit_comsetting_path(comsetting) %></td>
        <td><%#= link_to 'Destroy', comsetting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Comsetting', new_comsetting_path %>

app/views/comsettings/new_NONEWCOMS.html.erb
<h1>New comsetting</h1>

<%= render 'form' %>

<%= link_to 'Back', rasberry_pis_path %>

app/views/comsettings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comport:</strong>
  <%= @comsetting.comport %>
</p>

<p>
  <strong>Baud:</strong>
  <%= @comsetting.baud %>
</p>

<%= link_to 'Edit', edit_comsetting_path(@comsetting) %> |
<%= link_to 'Back', rasberry_pis_path %>