config/routes.rb
Monster::Application.routes.draw do
  resources :singlescenes

  resources :comsettings

  resources :rasberry_pis

  match '/', to: 'static_pages#home', via: 'get', as: :home
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/changecomsettings', to: 'static_pages#changecomsettings', via: 'get', as: :changecomsettings
  resources :scenes
  post 'rasberry_pis/shutdown' => 'rasberry_pis#shutdown', as: :shutdown_pi
  post 'scenes/:id/invoke' => 'scenes#invokescene', as: :invoke
  post 'scenes/stop_animation' => 'scenes#stop_animation', as: :stop_animation
  post 'scenes/stop_ambient' => 'scenes#stop_ambient', as: :stop_ambient
  post 'scenes/start_ambient' => 'scenes#start_ambient', as: :start_ambient
  post 'scenes/sequential_mode' => 'scenes#sequential_mode', as: :sequential_mode
  get 'singlescenes/1/edit' => 'singlescenes#edit', as: :single_mode
  post 'scenes/random_mode' => 'scenes#random_mode', as: :random_mode
  post 'scenes/refresh_scenes' => 'scenes#refresh_scenes', as: :refresh_scenes
  post 'rasberry_pis/reconnect_to_arduino' => 'rasberry_pis#reconnect_to_arduino', as: :reconnect_to_arduino
  

  root 'static_pages#home'

  

end

app/models/rasberry_pi.rb
class RasberryPi < ActiveRecord::Base
end

app/controllers/rasberry_pis_controller.rb
class RasberryPisController < ApplicationController
  before_action :set_rasberry_pi, only: [:show, :edit, :update, :destroy]

  # GET /rasberry_pis
  # GET /rasberry_pis.json
  def index
    @rasberry_pis = RasberryPi.all
    @comsettings = Comsetting.all
  end

  # GET /rasberry_pis/1
  # GET /rasberry_pis/1.json
  def show
  end
  
  def shutdown
    @rasberry_pis = RasberryPi.all
    Net::SSH.start(@rasberry_pis.first.ipdns, @rasberry_pis.first.username, :password => @rasberry_pis.first.password) do |ssh|
      ssh.exec "sudo shutdown -h -P now"
    end

  end
  
  
  # GET /rasberry_pis/new
  def new
    @rasberry_pi = RasberryPi.new
  end

  # GET /rasberry_pis/1/edit
  def edit
  end

  # POST /rasberry_pis
  # POST /rasberry_pis.json
  # at this time, the application only supports 1 pi
=begin
 
  def create
    @rasberry_pi = RasberryPi.new(rasberry_pi_params)

    respond_to do |format|
      if @rasberry_pi.save
        format.html { redirect_to @rasberry_pi, notice: 'Rasberry pi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rasberry_pi }
      else
        format.html { render action: 'new' }
        format.json { render json: @rasberry_pi.errors, status: :unprocessable_entity }
      end
    end
  end

=end 


  # PATCH/PUT /rasberry_pis/1
  # PATCH/PUT /rasberry_pis/1.json
  def update
    respond_to do |format|
      if @rasberry_pi.update(rasberry_pi_params)
        format.html { redirect_to :rasberry_pis, notice: 'Rasberry pi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rasberry_pi.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def reconnect_to_arduino
    @comsettings = Comsetting.all
    begin
       $PORT = SerialPort.new(@comsettings.first.comport,@comsettings.first.baud)
    rescue
       $CONNECTED = "fail"
       redirect_to :changecomsettings
    else 
    $CONNECTED = "pass"
    #this thread is necessary for keeping the ambient loop open
    #without this, the arduino is filling up with garbage and we can't send commands
      thread2 = Thread.new do
          while true do
              while (i = $PORT.gets.chomp) do 
                  #puts i
              end
          end
      end
    redirect_to :back
    end
  end
  # DELETE /rasberry_pis/1
  # DELETE /rasberry_pis/1.json
  # we can't have any mistakes now, can we?
=begin
  
  def destroy
    @rasberry_pi.destroy
    respond_to do |format|
      format.html { redirect_to rasberry_pis_url }
      format.json { head :no_content }
    end
  end
  
=end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rasberry_pi
      @rasberry_pi = RasberryPi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rasberry_pi_params
      params.require(:rasberry_pi).permit(:ipdns, :username, :password)
    end
end

app/helpers/rasberry_pis_helper.rb
module RasberryPisHelper
end

app/views/rasberry_pis/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="well">
              <%= form_for @rasberry_pi, :html => {:class => "form-horizontal"} do |f| %>
				  <% if @rasberry_pi.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@rasberry_pi.errors.count, "error") %> prohibited this jumpsquare from being saved:</h2>
				
				      <ul>
				      <% @rasberry_pi.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>        
                <fieldset>
                  <legend>Raspberry Pi: <%= @rasberry_pi.ipdns %></legend>
                  <div class="form-group">
                  	<%= f.label :ipdns, "IP Address or DNS Name:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.text_field :ipdns, :class => "form-control" %>	 
                    </div>
                  </div>
                  <br>  
                  <div class="form-group">
                  	<%= f.label :username, "Username:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.text_field :username, :class => "form-control" %>	 
                    </div>
                  </div>
                  <br>   
                  <div class="form-group">
                  	<%= f.label :password, "Password:", :class => "col-lg-4 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.password_field :password, :class => "form-control" %>	 
                    </div>
                  </div>                                              
                  <center>
	                  <div class="form-group">	                  	                  
	                      <%= f.submit class: 'btn btn-primary'%>	                    
	                  </div> 
			<% end %>	                              
	                  <%= link_to :back, class: "pull-left", :method => :get do %>
	        			 Back
	    			  <% end %>
	                     
	                  <%= link_to :home, class: "pull-right", :method => :get do %>
	        			Home
	    			  <% end %>       
                  </center>
                </fieldset>
             
            </div>
          </div>
        </div>
</html>

app/views/rasberry_pis/edit.html.erb
<br>
<%= render 'form' %>

app/views/rasberry_pis/index.html.erb
<% provide(:title, 'Settings') %>
<!DOCTYPE html>
  <head>
    <title><% :title %>	</title>
  </head>
  
<div class="row">
  	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  		<br>
  		<center><div id="notice"><span class="label label-success"><%= notice %></span></div><div id="alert"><span class="label label-danger"><%= alert %></span></div></center>
		<center><h3>Raspberry Pi/Server Settings</h3></center>
		<body>
			These settings will enable you to remotely shutdown a Raspberry Pi or linux based machine that accepts the "shutdown" command. 
			Shutting down your Raspberry Pi using native linux commands will minimize risk to file corruption. These settings do not change or manipulate the Raspberry Pi			
			<br>
				<table class="table table-striped table-bordered table-hover">
	                <thead>
	                  <tr>
	                    <th>IP Address or DNS Name</th>
					    <th>User</th>
					    <th>Password</th>
					    <th></th>
	                  </tr>
	                </thead>	                
	                	<tbody>
	                		<% @rasberry_pis.each do |rasberry_pi| %>
							      <tr>
							        <td><%= rasberry_pi.ipdns %></td>
							        <td><%= rasberry_pi.username %></td>
							        <td>&#9679&#9679&#9679&#9679&#9679&#9679&#9679&#9679</td>					        
							        <td><%= link_to 'Edit', edit_rasberry_pi_path(rasberry_pi), method: :get, class: "btn btn-warning btn-xs" %></td>						   
							      </tr>
							<% end %>
						</tbody>               
	            </table>
			<br>
			<br>
			The settings will change how your Pi/Server is interacting with the MonsterShield. Set the communications port of your server accordingly.
			  ttyACM0 is usually default in Raspberry Pi configurations. ttyUSB configurations are used for linux. usbmodem are used in Mac configurations. COM are used in PC configurations. Only Raspberry Pi and Mac configurations have been tested.
			   The MonsterShield baud rate is 115200 by default.
			<br>
				<table class="table table-striped table-bordered table-hover">
	                <thead>
	                  <tr>
	                    <th>Communications Port</th>
					    <th>Baud Rate</th>
					    <th></th>
	                  </tr>
	                </thead>	                
	                	<tbody>
	                		<% @comsettings.each do |comsetting| %>
							      <tr>
							        <td><%= comsetting.comport %></td>
							        <td><%= comsetting.baud %></td>				        
							        <td><%= link_to 'Edit', edit_comsetting_path(comsetting), method: :get, class: "btn btn-warning btn-xs" %></td>						   
							      </tr>
							<% end %>
						</tbody>               
	            </table>
		<br>
		<center>
		    		<% if $CONNECTED == 'fail' %>
		    			<span class="label label-danger">MonsterShield Disconnected</span>	
		    			<%= button_to "Connect MonsterShield", :reconnect_to_arduino, class: "btn btn-med btn-warning", :method => :post %>		
					<% elsif $CONNECTED == 'pass' %>
		      			<span class="label label-success">MonsterShield Connected</span>
		      		<% end %>	
		<br>
			<div style="float:center;margin-right:10px;margin-bottom: 10px;">
	      			<%= button_to "Shutdown Pi", shutdown_pi_path, class: "btn btn-large btn-danger", data: { confirm: "Warning!   Are you sure?"}, :method => :post %> 
	     	</div>
	    </center>
	    			
		</body>
	</div>
</div>

</html>

app/views/rasberry_pis/new.html.erb
<h1>New rasberry_pi</h1>

<%= render 'form' %>

<%= link_to 'Back', rasberry_pis_path %>

app/views/rasberry_pis/new_NOMOREPIS.html.erb
<h1>New rasberry_pi</h1>

<%= render 'form' %>

<%= link_to 'Back', rasberry_pis_path %>

app/views/rasberry_pis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IP Address or DNS Name:</strong>
  <%= @rasberry_pi.ipdns %>
</p>

<p>
  <strong>Username:</strong>
  <%= @rasberry_pi.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @rasberry_pi.password %>
</p>

<%= link_to 'Edit', edit_rasberry_pi_path(@rasberry_pi) %> |
<%= link_to 'Back', rasberry_pis_path %>

app/views/rasberry_pis/shutdown.html.erb
<p>Your Pi/Server is shutting down...wait about 30 seconds to 1 minute and you can turn off the power</p> 